### ISSUE TITLE
is there any tools to scan project and generate .evc file or String？

### ISSUE THREAD

**Issue by zmtzawqlp** [ethanblake4/flutter_eval#1]
is there any tools to scan project and generate .evc file or String？

add an annotate and scan project , then generate file for service download

**Comment by ethanblake4** [comment]
Hi, 
dart_eval has a CLI which can do this but it does not support bindings (so it can't work with flutter_eval). I definitely plan on adding binding support soon.

**Comment by ethanblake4** [comment]
Completed in https://github.com/ethanblake4/flutter_eval/commit/b3fdd44be92e1f0e339cb57b407d970498202023. Instructions for compiling an existing project are now [in the readme](https://pub.dev/packages/flutter_eval#compiling-with-the-dart_eval-cli).
