### ISSUE TITLE
package solving failed.

### ISSUE THREAD

**Issue by normidar** [ethanblake4/flutter_eval#17]
[quick_ide] flutter pub get
Running "flutter pub get" in quick_ide...                       
Because flutter_eval >=0.5.3 depends on dart_eval ^0.5.4 which depends on dcli ^1.34.0, flutter_eval >=0.5.3 requires dcli ^1.34.0.
And because dcli >=1.33.2 <2.0.0-beta.13 depends on win32 ^2.7.0, flutter_eval >=0.5.3 requires win32 ^2.7.0.
And because file_picker 5.2.2 depends on win32 ^3.0.0 and no versions of file_picker match >5.2.2 <6.0.0, flutter_eval >=0.5.3 is incompatible with file_picker ^5.2.2.
So, because quick_ide depends on both file_picker ^5.2.2 and flutter_eval ^0.5.3, version solving failed.
pub get failed (1; So, because quick_ide depends on both file_picker ^5.2.2 and flutter_eval ^0.5.3, version solving failed.)
exit code 1

**Comment by normidar** [comment]
can you update packages please?

**Comment by normidar** [comment]
I am trying to use file_picker to pick some files and open them by flutter_eval.
Isn’t it a good idea ?

**Comment by ethanblake4** [comment]
The latest version of dcli still depends on win32 ^2.7.0 so there's nothing I can do about this. Please file an issue with dcli or use an older version of file_picker.

**Comment by anz-ryu** [comment]
is flutter_eval need dcli?
Maybe  flutter_eval do not need depends dart_eval, some dart_eval package is not required.

**Comment by ethanblake4** [comment]
@anz-ryu @normidar I filed [an issue](https://github.com/ethanblake4/dart_eval/issues/75) to remove dcli, I didn't realize how bloated it was. It's features are used in the dart_eval CLI but I only use a few of them so it shouldn't be too hard to replace.

**Comment by normidar** [comment]
@ethanblake4 
thank you, I am using `file_picker: 5.0.1` now. close this issue.
