### ISSUE TITLE
InkWell

### ISSUE THREAD

**Issue by aktxyz** [ethanblake4/flutter_eval#21]
Any chance InkWell is on your shortlist of things to add support for?  
That jumped out as the 1 missing thing that would prevent making a good go at playing around with this.

Or maybe some other way to bubble multiple types of tap events up from a flutter_eval'd widget?

**Comment by ethanblake4** [comment]
Sure, I'll add it in the next release.

**Comment by ethanblake4** [comment]
Completed in v0.6.0
