### ISSUE TITLE
passing domain object to EvalWidget

### ISSUE THREAD

**Issue by aktxyz** [ethanblake4/flutter_eval#23]
The example shows how to pass a string into an EvalWidget like so ...

```
args: [$String('Example name')]
```

Can you provide an example for passing an instance of domain class into EvalWidget, both the on the dart side (args: ..) and in the eval'd code string.  It seems there also needs to be way to make the eval'd code aware of the class def, normally an import.

**Comment by ethanblake4** [comment]
Closing as duplicate of https://github.com/ethanblake4/dart_eval/issues/79
