### ISSUE TITLE
Load program.evc from the network, the screen cannot be displayed normally.

### ISSUE THREAD

**Issue by tenSunFree** [ethanblake4/flutter_eval#24]
Load program.evc from the network, the screen cannot be displayed normally.
![001](https://user-images.githubusercontent.com/23090085/203849763-3b9332b1-b7ca-446a-9cd0-2d94b106bfc5.jpg)

If you need to refresh the screen again after successfully reading the data, you can consider adding setState().
![002](https://user-images.githubusercontent.com/23090085/203849786-401595ae-8b63-408d-9450-c9ba6c253dcd.jpg)

**Comment by ethanblake4** [comment]
Fixed in v0.5.4
