### ISSUE TITLE
Add `BridgeWidgetClassDef` specific to flutter_eval

### ISSUE THREAD

**Issue by canewsin** [ethanblake4/flutter_eval#34]
Below params for class `BridgeClassDef` are marked as required, yet almost all Widgets don't need to access these params especially `getter, setters, methods`, thus for every Widget, instead of leaving them empty. We can add `BridgeWidgetClassDef` in flutter_eval. If user needs such params, he can use `BridgeClassDef`.

```dart
  final Map<String, BridgeMethodDef> methods;
  final Map<String, BridgeMethodDef> getters;
  final Map<String, BridgeMethodDef> setters;
  final Map<String, BridgeFieldDef> fields;
```
Thoughts ?

**Comment by ethanblake4** [comment]
Upcoming v0.6 version of dart_eval will no longer mark these params as required.
