### ISSUE TITLE
Running the example fails with type 'MainAxisSize' is not a subtype of type 'MainAxisAlignment'

### ISSUE THREAD

**Issue by g123k** [ethanblake4/flutter_eval#4]
Hi!

It seems there is an issue with the Column Widget, where the mapping between MainAxisSize and MainAxisAlignment is shuffled. Just by running the example, you should have this error:

`dart_eval runtime exception: type 'MainAxisSize' is not a subtype of type 'MainAxisAlignment'`

**Comment by ethanblake4** [comment]
Thanks so much! I published 0.4.4 on Pub with your fix
