### ISSUE TITLE
Error: The non-abstract class '$BuildContext' is missing implementations for these members:  - BuildContext.mounted

### ISSUE THREAD

**Issue by keyskull** [ethanblake4/flutter_eval#40]
Flutter (Channel stable, 3.7.0, on Microsoft Windows [Version 10.0.22621.1194], locale en-US)

**Comment by ethanblake4** [comment]
Fixed in https://github.com/ethanblake4/flutter_eval/commit/f04f972f43f8b7bea917025b4c50a90e297b7244
