### ISSUE TITLE
EvalPad doesn't allow rotating the screen after installed

### ISSUE THREAD

**Issue by dhombios** [ethanblake4/flutter_eval#42]
I couldn't find the repo of EvalPad, so flutter_eval repo seems the best place to report this.

Using EvalPad in the browser allows using it in landscape mode, but after installing it as a pwa it does no longer rotate. As a result, it is always displayed in portrait mode on android smartphones.

Probably this is a consequence of the chosen orientation field in the manifest

**Comment by ethanblake4** [comment]
Should be fixed now :)
