### ISSUE TITLE
TextStyle error

### ISSUE THREAD

**Issue by yakppal** [ethanblake4/flutter_eval#46]
`import 'package:flutter/material.dart';

class MyApp extends StatefulWidget {
  const MyApp({super.key});
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  int number = 0;

  void incrementNumber() {
    setState(() {
      number += 2;
    });
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title:  Text('Number Incrementer'),
        ),
        body: Center(
          child: Text(
            '$number',
             style: TextStyle(fontSize: 48)
            ),
        ),
        floatingActionButton: FloatingActionButton(
          onPressed: () {
            incrementNumber();
          },
          child: const Icon(Icons.add),
        ),
      ),
    );
  }
}
`

1. When I insert the code above, it crashes. If I remove style: TextStyle(fontSize: 48), it runs OK. I tried both CompilerWidget and EvalWidget. What could be the issue? 

![Screenshot 2023-03-10 at 11 07 27 PM](https://user-images.githubusercontent.com/65849424/224336881-5dae0159-fb0a-49e3-bfa1-0699b30d9038.png)
![Screenshot 2023-03-10 at 11 07 40 PM](https://user-images.githubusercontent.com/65849424/224336900-5ba0c326-cd31-4803-aa66-faf90e5e5401.png)

**Comment by ethanblake4** [comment]
Hi,

This is a bug that I'll fix in the next release.
In the meantime you should be able to work around it by specifying `inherit: true` in the TextStyle constructor.

**Comment by yakppal** [comment]
Thank you for such a quick response. I'm testing out both dartpad and flutter_eval. Is there any other known issues like TextStyle?

**Comment by ethanblake4** [comment]
This wasn't a known issue actually, I just looked into it because you opened this issue and figured out what was going on. There's nothing else that I know of.

**Comment by ethanblake4** [comment]
Fixed in v0.6.0
