### ISSUE TITLE
Catching error

### ISSUE THREAD

**Issue by yakppal** [ethanblake4/flutter_eval#47]
It would be nice if we can catch error from EvalWidget/CompileWidget. If there's an error, I can show the syntax error on screen. Is there any other way to detect compile error?

**Comment by yakppal** [comment]
@override
  Widget build(BuildContext context) {
    try {
      return EvalWidget();
    } catch (e) {
      return Text(e.message);
    }
  }

![Screenshot 2023-03-11 at 7 35 41 AM](https://user-images.githubusercontent.com/65849424/224441097-69ab64a5-0442-438c-a744-d3336ec888a8.png)

It would something like this. I need to show the errors of the code.

**Comment by ethanblake4** [comment]
Completed in v0.6.0. There is a new `onError` property in EvalWidget (and RuntimeWidget / CompilerWidget) you can use to create a custom error display.
