### ISSUE TITLE
Question: Is this performant enough for a complicated list view to smoothly update/view?

### ISSUE THREAD

**Issue by rockingdice** [ethanblake4/flutter_eval#60]
Is there any performance data for comparison of native flutter and flutter_eval? I'm very curious if the ui is smooth enough when using this library.
My concern is a busy-updating list view, it contains a lot of items and many of them need to be updated when scrolling. Did you have some examples to show the performance? 
Thank you.

**Comment by ethanblake4** [comment]
Hi! The dart_eval VM is around 10-15x slower than Dart native, but that only applies to the code you **directly** write. Any code that's part of Flutter will run at the same speed, and so this usually means that apps see little to no performance issues with flutter_eval. Each use case is different, and you might as well test it out :)
