### ISSUE TITLE
Navigator.push not supported

### ISSUE THREAD

**Issue by Z6P0** [ethanblake4/flutter_eval#66]
The class `Navigator` is marked as supported, however `Navigator.push` does not compile:

> Cannot find static method Navigator.push

Same with `Navigator.of(context).push`:

> Unknown method NavigatorState.push

**Comment by ethanblake4** [comment]
`pushNamed` is supported, can you use that? Or do you need `push` specifically for your use case?

**Comment by Z6P0** [comment]
In fact I'd like to use flutter_eval or dart_eval for building anti-piracy protection.
My idea is to put some application code (for example navigation) in bytecode, along with some protection code like flutter_security_checker, to defeat cracking software.
I don't know if it can work?
