### ISSUE TITLE
Apple App Store guidelines.

### ISSUE THREAD

**Issue by gbumps** [ethanblake4/flutter_eval#7]
The lib is cool. However, I'm still concern about Apple approval for this library when submitting app for review. As described In License agreement and section 2.5.2 of AppStore Review Guidelines, an interpreted code may be downloaded to application but may not change the primarily purpose of the app nor changing the whole app binary structure.

**Comment by ethanblake4** [comment]
Yep, this lib operates in a bit of a gray area within the App Store guidelines, you should use it at your own risk.
