### ISSUE TITLE
Align not work

### ISSUE THREAD

**Issue by raymondtruongdev** [ethanblake4/flutter_eval#78]
I saw your code is support Align(). However, in my code Align() do not work ( I can build EVC file sucessfullly ), If I remove  **Align( alignment: Alignment.center,**) the programe will workwell

`library watch_face;

import 'package:eval_annotation/eval_annotation.dart';
import 'package:flutter/material.dart';
import 'package:flutter/widgets.dart';

@RuntimeOverride('#myapp_main_scaffold_1')
Widget scaffoldUpdate(BuildContext context) {
  return Scaffold(
    body: Center(
        child: Container(
            width: 390,
            height: 390,
            color: Colors.black,
            child: const Column(
              // Change to Column
              mainAxisAlignment:
                  MainAxisAlignment.spaceBetween, // Align at the bottom and top
              children: [
                Center(
                  child: Text(
                    "04",
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: 130.0,
                      fontWeight: FontWeight.bold,
                    ),
                  ),
                ),
                Center(
                    child: Row(
                        mainAxisAlignment: MainAxisAlignment.center,
                        children: [
                      Text(
                        "44",
                        style: TextStyle(
                          color: Colors.white,
                          fontSize: 100.0,
                          fontWeight: FontWeight.bold,
                        ),
                      ),
                      SizedBox(
                        width: 10,
                      ),
                      Text(
                        "30",
                        style: TextStyle(
                          color: Colors.green,
                          fontSize: 80.0,
                          fontWeight: FontWeight.bold,
                        ),
                      ),
                    ])),
                Align(
                      alignment: Alignment.center,
                  child: Text(
                    "PM",
                    style: TextStyle(
                      color: Colors.blue,
                      fontSize: 30.0,
                      fontWeight: FontWeight.bold,
                    ),
                  ),
                ),
              ],
            ))),
  );
}
`

**Comment by ethanblake4** [comment]
Fixed in v0.7.5
