### ISSUE TITLE
Compiling widgets implemented in multiple files

### ISSUE THREAD

**Issue by dhombios** [ethanblake4/flutter_eval#91]
I find flutter_eval quite useful for implementing apps for teaching flutter (like a more advanced dartpad). However, all examples I've found implement the dynamic widget using a single .dart file

Would it be possible to use multiple files (a main one and others that are imported from it)? That would be great for teaching how to structure flutter projects (dartpad's single file limitation can be a limitation for advanced tutorials)

**Comment by ethanblake4** [comment]
Of course, that is supported. If you are using CompilerWidget for example, like this:

```dart
return CompilerWidget(packages: {
  'example': {
    'main.dart': '''
      import 'package:flutter/material.dart';
      import 'package:example/my_widget.dart';
      Widget getWidget() {
        return MyWidget();
      }
     ''',
     'my_widget.dart': '''
       import 'package:flutter/material.dart';
       class MyWidget extends StatelessWidget { 
         //...
       }
     '''
    }
  },
  library: 'package:example/main.dart',
  function: 'getWidget',
});
